server:
  port: 9000

spring:
  application:
    name: poc-clean-architecture
  data:
    mongodb:
      database: POC
      uri: mongodb://localhost:27017/myDb
      username: poc-clean-arch
      password: pass

  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            jdbc: DataSourceAutoConfiguration

graphql.playground:
  mapping: /playground
  endpoint: /graphql
  enabled: true
  pageTitle: Playground
  cdn:
    enabled: true
    version: latest
  settings:
    request.credentials: omit
    schema.polling.enable: false

# Logs
logging:
  level:
    ROOT: ${LOG_ROOT_LEVEL:INFO}