server:
  port: 9000

spring:
  application:
    name: poc-clean-architecture
  data:
    mongodb:
      database: POC
      uri: mongodb://localhost:27017/myDb
      username: poc-clean-arch
      password: pass

  autoconfigure:
    exclude=org:
      springframework:
        boot:
          autoconfigure:
            jdbc: DataSourceAutoConfiguration
